from PyQt5 import QtCore, QtGui, QtWidgets
import Mr_cheragui_TP as TP
import sys , time
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Submit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Submit.setGeometry(QtCore.QRect(290, 480, 231, 41))
        self.pushButton_Submit.setObjectName("pushButton_Submit")
        self.lineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1.setGeometry(QtCore.QRect(40, 240, 91, 41))
        self.lineEdit1.setObjectName("lineEdit1")
        self.lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2.setGeometry(QtCore.QRect(150, 240, 91, 41))
        self.lineEdit2.setObjectName("lineEdit2")
        self.lineEdit3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit3.setGeometry(QtCore.QRect(260, 240, 91, 41))
        self.lineEdit3.setObjectName("lineEdit3")
        self.lineEdit7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit7.setGeometry(QtCore.QRect(40, 360, 91, 41))
        self.lineEdit7.setObjectName("lineEdit7")
        self.lineEdit6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit6.setGeometry(QtCore.QRect(260, 300, 91, 41))
        self.lineEdit6.setObjectName("lineEdit6")
        self.lineEdit5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit5.setGeometry(QtCore.QRect(150, 300, 91, 41))
        self.lineEdit5.setObjectName("lineEdit5")
        self.lineEdit4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit4.setGeometry(QtCore.QRect(40, 300, 91, 41))
        self.lineEdit4.setObjectName("lineEdit4")
        self.lineEdit8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit8.setGeometry(QtCore.QRect(150, 360, 91, 41))
        self.lineEdit8.setObjectName("lineEdit8")
        self.lineEdit9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit9.setGeometry(QtCore.QRect(260, 360, 91, 41))
        self.lineEdit9.setObjectName("lineEdit9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 90, 741, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 741, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 540, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(80, 220, 49, 16))
        self.label1.setObjectName("label1")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 220, 49, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 220, 49, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 280, 49, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 280, 49, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(300, 280, 49, 16))
        self.label_10.setObjectName("label_10")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 340, 49, 16))
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(300, 340, 49, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(190, 340, 49, 16))
        self.label_12.setObjectName("label_12")
        self.label1_2 = QtWidgets.QLabel(self.centralwidget)
        self.label1_2.setGeometry(QtCore.QRect(490, 220, 49, 16))
        self.label1_2.setObjectName("label1_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(710, 220, 49, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(600, 340, 49, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit2_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2_2.setGeometry(QtCore.QRect(560, 240, 91, 41))
        self.lineEdit2_2.setObjectName("lineEdit2_2")
        self.lineEdit7_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit7_2.setGeometry(QtCore.QRect(450, 360, 91, 41))
        self.lineEdit7_2.setObjectName("lineEdit7_2")
        self.lineEdit6_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit6_2.setGeometry(QtCore.QRect(670, 300, 91, 41))
        self.lineEdit6_2.setObjectName("lineEdit6_2")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(420, 220, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lineEdit9_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit9_2.setGeometry(QtCore.QRect(670, 360, 91, 41))
        self.lineEdit9_2.setObjectName("lineEdit9_2")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(490, 340, 49, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(600, 280, 49, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(710, 280, 49, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(710, 340, 49, 16))
        self.label_19.setObjectName("label_19")
        self.lineEdit1_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1_2.setGeometry(QtCore.QRect(450, 240, 91, 41))
        self.lineEdit1_2.setObjectName("lineEdit1_2")
        self.lineEdit8_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit8_2.setGeometry(QtCore.QRect(560, 360, 91, 41))
        self.lineEdit8_2.setObjectName("lineEdit8_2")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(600, 220, 49, 16))
        self.label_20.setObjectName("label_20")
        self.lineEdit5_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit5_2.setGeometry(QtCore.QRect(560, 300, 91, 41))
        self.lineEdit5_2.setObjectName("lineEdit5_2")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(490, 280, 49, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit3_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit3_2.setGeometry(QtCore.QRect(670, 240, 91, 41))
        self.lineEdit3_2.setObjectName("lineEdit3_2")
        self.lineEdit4_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit4_2.setGeometry(QtCore.QRect(450, 300, 91, 41))
        self.lineEdit4_2.setObjectName("lineEdit4_2")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(160, 170, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(570, 170, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Submit.setText(_translate("MainWindow", "Submit"))
        self.label.setText(_translate("MainWindow", "input the values of the matrics one by one then press Submit "))
        self.label_2.setText(_translate("MainWindow", "A* ALgorithm TP Implemented for 8 puzzle Game"))
        self.label_3.setText(_translate("MainWindow", "Created by : Abdedaiem amin"))
        self.label_4.setText(_translate("MainWindow", "i = "))
        self.label1.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "2"))
        self.label_8.setText(_translate("MainWindow", "3"))
        self.label_9.setText(_translate("MainWindow", "4"))
        self.label_10.setText(_translate("MainWindow", "5"))
        self.label_5.setText(_translate("MainWindow", "6"))
        self.label_11.setText(_translate("MainWindow", "8"))
        self.label_12.setText(_translate("MainWindow", "7"))
        self.label1_2.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "2"))
        self.label_14.setText(_translate("MainWindow", "7"))
        self.label_15.setText(_translate("MainWindow", "i = "))
        self.label_16.setText(_translate("MainWindow", "6"))
        self.label_17.setText(_translate("MainWindow", "4"))
        self.label_18.setText(_translate("MainWindow", "5"))
        self.label_19.setText(_translate("MainWindow", "8"))
        self.label_20.setText(_translate("MainWindow", "1"))
        self.label_21.setText(_translate("MainWindow", "3"))
        self.label_22.setText(_translate("MainWindow", "Etat Initial"))
        self.label_23.setText(_translate("MainWindow", "Etat Final"))

        self.pushButton_Submit.clicked.connect(self.save_init)

    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("result")
        msg.setText("found solution after : " + str(self.res) + "moves")

        x = msg.exec_()

    def save_init(self):
        self.l , self.m = [] , []
        self.l.append(int(self.lineEdit1.text()))
        self.l.append(int(self.lineEdit2.text()))
        self.l.append(int(self.lineEdit3.text()))
        self.l.append(int(self.lineEdit4.text()))
        self.l.append(int(self.lineEdit5.text()))
        self.l.append(int(self.lineEdit6.text()))
        self.l.append(int(self.lineEdit7.text()))
        self.l.append(int(self.lineEdit8.text()))
        self.l.append(int(self.lineEdit9.text()))
        self.m.append(int(self.lineEdit1_2.text()))
        self.m.append(int(self.lineEdit2_2.text()))
        self.m.append(int(self.lineEdit3_2.text()))
        self.m.append(int(self.lineEdit4_2.text()))
        self.m.append(int(self.lineEdit5_2.text()))
        self.m.append(int(self.lineEdit6_2.text()))
        self.m.append(int(self.lineEdit7_2.text()))
        self.m.append(int(self.lineEdit8_2.text()))
        self.m.append(int(self.lineEdit9_2.text()))
        TP.get_game(self.m)
        sys.setrecursionlimit(5000)
        # start = time.time()
        self.res = TP.solve(self.l, self.m,3)
        self.show_popup()
        
        


if __name__ == "__main__":
    import sys
    start = time.time()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    end = time.time()
    print("this task took %f ms" % (end - start))
    sys.exit(app.exec_())
    
